### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by ifvictr** [ifvictr/rebrandly#1]
Each test will test one functionality. Tests will be located under `test/` and use the AVA testing framework.

**Comment by adrichey** [comment]
Do you have a preference on a testing framework for this? Mocha or Jasmine? If you can update this issue with a preference, I will get started on writing some tests around this. Thanks and happy Hacktoberfest!

**Comment by ifvictr** [comment]
@adrichey I prefer the [AVA](https://github.com/avajs/ava) testing framework. Thanks!

**Comment by adrichey** [comment]
Sounds good. I haven't worked with AVA before. Looks interesting! I will get started on getting the testing base in place early this week and exploring the codebase.

**Comment by adrichey** [comment]
Submitted PR #3 for your review!
